"use client";
import {useState} from "react";
import styles from "./styles.module.css";
type Appearance="light"|"dark";
type Concept={id:number;name:string;note:string;tone:string;lightBg:string;darkBg:string;lightBack:string;darkBack:string;a1:string;a2:string;split:boolean;grid:number;glass?:boolean;rotation:number};
const concepts:Concept[]=[
{id:1,name:"双页 · 蓝橙循环",note:"标准双箭循环，白班与夜班用两种颜色首尾相接",tone:"双色 · 均衡",lightBg:"#7254D9",darkBg:"#0A1020",lightBack:"#B5A6F1",darkBack:"#293054",a1:"#FFB52A",a2:"#6C51DB",split:true,grid:.07,glass:true,rotation:8},
{id:2,name:"双页 · 深蓝循环",note:"同色双箭构成完整循环，稳重且识别直接",tone:"同色 · 稳重",lightBg:"#2879DF",darkBg:"#071529",lightBack:"#7BAAF0",darkBack:"#17385C",a1:"#174C9D",a2:"#4FB2FF",split:false,grid:.05,rotation:7},
{id:3,name:"双页 · 天蓝循环",note:"更轻、更细的标准双箭循环，日期格接近隐去",tone:"同色 · 轻盈",lightBg:"#EAF3FF",darkBg:"#0A1B32",lightBack:"#D3E3F7",darkBack:"#203B5B",a1:"#1974EF",a2:"#59B7FF",split:false,grid:.035,glass:true,rotation:6},
{id:4,name:"双页 · 蓝紫循环",note:"两段箭头分色，但轮廓仍是最标准的圆形循环",tone:"双色 · 夜色",lightBg:"#3143AA",darkBg:"#050B18",lightBack:"#6975D1",darkBack:"#1A2948",a1:"#47A9FF",a2:"#9870FF",split:true,grid:.06,glass:true,rotation:8},
{id:5,name:"单页 · 珊瑚循环",note:"暖色背景配同色双箭，减少日历以外的干扰",tone:"同色 · 扁平",lightBg:"#FF765F",darkBg:"#211011",lightBack:"#D94E46",darkBack:"#4A282B",a1:"#D94235",a2:"#FF8A79",split:false,grid:.04,rotation:5},
{id:6,name:"单页 · 绿色循环",note:"完全取消日期格，只保留日历和标准双箭循环",tone:"同色 · 极简",lightBg:"#209C75",darkBg:"#071B16",lightBack:"#117055",darkBack:"#173C32",a1:"#087254",a2:"#4ED5A5",split:false,grid:0,rotation:4},
{id:7,name:"双页 · 青色循环",note:"柔和玻璃层与同色双箭，清爽但不轻飘",tone:"同色 · 清爽",lightBg:"#1AA7B5",darkBg:"#06191E",lightBack:"#77D0D5",darkBack:"#17434B",a1:"#086F7D",a2:"#4DD8E5",split:false,grid:.04,glass:true,rotation:7},
{id:8,name:"双页 · 多彩循环",note:"保持标准循环轮廓，只用颜色区分两类班次",tone:"双色 · 多彩",lightBg:"#F0F2F6",darkBg:"#101319",lightBack:"#D9DEE8",darkBack:"#303744",a1:"#FF9F24",a2:"#347BE9",split:true,grid:.04,rotation:6},
{id:9,name:"双页 · 靛蓝循环",note:"同色双箭形成完整闭环，日期格只作轻微陪衬",tone:"同色 · 层次",lightBg:"#3C4DB8",darkBg:"#090D24",lightBack:"#727DDD",darkBack:"#272F62",a1:"#3548B8",a2:"#8798FF",split:false,grid:.035,glass:true,rotation:8},
{id:10,name:"10 号 · 标准循环",note:"保留紫色双页玻璃，用最正常的圆形双箭头重画",tone:"双色 · 母版",lightBg:"#7352D8",darkBg:"#0D0920",lightBack:"#B6A5F5",darkBack:"#362C62",a1:"#FFB52A",a2:"#674CD1",split:true,grid:.05,glass:true,rotation:8},
{id:11,name:"双页 · 发光循环",note:"深色外观重点方案，两种模式保持同一标准结构",tone:"同色 · 发光",lightBg:"#DDEEFF",darkBg:"#061328",lightBack:"#A9C9EF",darkBack:"#173158",a1:"#258CEB",a2:"#38AFFF",split:false,grid:.035,glass:true,rotation:7},
{id:12,name:"双页 · 黑白循环",note:"用黑白灰建立层次，循环仍由完整双箭组成",tone:"同色 · 黑白",lightBg:"#F4F5F7",darkBg:"#08090B",lightBack:"#E0E3E8",darkBack:"#292C31",a1:"#202631",a2:"#F2F4F8",split:false,grid:.025,glass:true,rotation:6}];
function Head({x,y,a,c,s=8}:{x:number;y:number;a:number;c:string;s?:number}){return <path d={`M${x-s} ${y-s*.7}L${x+s} ${y}L${x-s} ${y+s*.7}Z`} fill={c} transform={`rotate(${a} ${x} ${y})`}/>}
function Cycle({c,dark}:{c:Concept;dark:boolean}){const base=dark?c.a2:c.a1,first=c.split?c.a1:base,second=c.split?c.a2:base,width=c.id===3?9:11;return <><path d="M70 117A32 32 0 0 1 123 94" fill="none" stroke={first} strokeWidth={width} strokeLinecap="round"/><Head x={128} y={98} a={42} c={first} s={c.id===3?7:8}/><path d="M130 111A32 32 0 0 1 77 134" fill="none" stroke={second} strokeWidth={width} strokeLinecap="round"/><Head x={72} y={130} a={222} c={second} s={c.id===3?7:8}/></>}
function Artwork({concept:c,appearance}:{concept:Concept;appearance:Appearance}){const dark=appearance==="dark",sh=`sh-${c.id}-${appearance}`,gl=`gl-${c.id}-${appearance}`,bg=dark?c.darkBg:c.lightBg,back=dark?c.darkBack:c.lightBack,page=dark?"#151D2A":"#FFFFFF",header=dark?"#222D3E":"#EEF2F7",ring=dark?"#91C6FF":"#FFFFFF",grid=dark?"#8296B6":"#426DE7";return <svg viewBox="0 0 200 200" role="img" aria-label={`${c.id} 号 ${c.name}，${appearance}`}><defs><filter id={sh} x="-40%" y="-40%" width="180%" height="190%"><feDropShadow dx="0" dy="7" stdDeviation="7" floodColor="#050816" floodOpacity={dark?".45":".22"}/></filter><linearGradient id={gl} x1=".1" y1="0" x2=".9" y2="1"><stop stopColor={page} stopOpacity=".98"/><stop offset="1" stopColor={dark?"#233047":"#DCE4F5"} stopOpacity=".84"/></linearGradient></defs><rect width="200" height="200" rx="44" fill={bg}/><rect x="61" y="38" width="98" height="109" rx="27" fill={back} transform={`rotate(${c.rotation} 110 93)`}/><g filter={`url(#${sh})`}><rect x="49" y="45" width="102" height="112" rx="27" fill={c.glass?`url(#${gl})`:page}/><path d="M49 77H151" stroke={header} strokeWidth="13"/><rect x="73" y="34" width="11" height="31" rx="5.5" fill={ring}/><rect x="116" y="34" width="11" height="31" rx="5.5" fill={ring}/><g opacity={c.grid}>{[0,1,2,3,4,5,6,7,8].map(n=><rect key={n} x={70+(n%3)*23} y={91+Math.floor(n/3)*22} width="13" height="12" rx="4" fill={grid}/>)}</g><Cycle c={c} dark={dark}/></g></svg>}
export default function IconLabPage(){const[appearance,setAppearance]=useState<Appearance>("light"),[selected,setSelected]=useState<number[]>([]),toggle=(id:number)=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):old.length<4?[...old,id]:[...old.slice(1),id]),dark=appearance==="dark";return <main className={`${styles.page} ${dark?styles.dark:""}`}><header className={styles.hero}><p className={styles.eyebrow}>SHIFT LEDGER · LIGHT / DARK</p><h1>一个标准循环，两套自然外观</h1><p className={styles.intro}>第五轮统一使用完整的圆形双箭循环，不再出现 C 字开口或异形环。浅色和深色不是简单反相，而是分别调整日历纸张、后页、日期格和箭头亮度。</p></header><nav className={styles.filters} aria-label="外观切换"><button className={!dark?styles.active:""} onClick={()=>setAppearance("light")}>浅色外观</button><button className={dark?styles.active:""} onClick={()=>setAppearance("dark")}>深色外观</button></nav>{selected.length>0&&<section className={styles.compare}><div><strong>正在对比</strong><span>最多 4 款</span></div><div className={styles.compareItems}>{selected.map(id=>{const c=concepts[id-1];return <button key={id} onClick={()=>toggle(id)}><i><Artwork concept={c} appearance={appearance}/></i><span>{String(id).padStart(2,"0")} · {c.name}</span><b>×</b></button>})}</div></section>}<section className={styles.grid}>{concepts.map(c=>{const chosen=selected.includes(c.id);return <article key={c.id} className={`${styles.card} ${chosen?styles.chosen:""}`}><button className={styles.artButton} onClick={()=>toggle(c.id)}><div className={styles.art}><Artwork concept={c} appearance={appearance}/></div><span className={styles.selectMark}>{chosen?"已加入对比":"加入对比"}</span></button><div className={styles.meta}><div className={styles.titleRow}><span>{String(c.id).padStart(2,"0")}</span><h2>{c.name}</h2></div><p>{c.note}</p><div className={styles.micro}><em>{c.tone}</em><i className={styles.s60}><Artwork concept={c} appearance={appearance}/></i><i className={styles.s40}><Artwork concept={c} appearance={appearance}/></i></div></div></article>})}</section><footer className={styles.footer}>先分别切换浅色和深色查看，再选构图。最终 Icon Composer 会继续输出系统 Tinted 与 Clear 外观。</footer></main>}
